### PR TITLE
Add support for ItemHold (long click/right click) event and Command

### PR DESCRIPTION
**Pull request by kipters**
Hi.

This pull requests adds support for the aforementioned event and relative Command in your GridView.

### CODE REVIEW

**Comment by Inrego** [comment]
Any reason this PR isn't merged? Is the project inactive, or?

**Comment by kipters** [comment]
I guess this project has been abandoned

**Comment by NobsterTheLobster** [comment]
Sorry Not abandoned. I just haven't been looking at it for awhile and git does not seem to send me notifications.  Also I'm new to the whole pull request thing. There was a conflict on the file XamarinFormsGridView/XamarinFormsGridView.Android/Resources/Resource.Designer.cs. I just removed the couple of lines that git was complaining about and clicked the merge. Hopefully that was correct.

**Comment by kipters** [comment]
Don't worry about that, I was considering adopting the project, but if you want I can help you with some of the issues 😊 You can safely ignore conflicts on that file and solve them however you want, it will be regenerated at compile time anyway. I'm yet to find the correct strategy for dealing with that one.

**Comment by NobsterTheLobster** [comment]
Sent you a collaboration invite which I hope should allow you edit the project without me having to merge each change. I'm still thinking that at some point Xamarin.Forms will release a proper gridview control themselves so I'm not really focused on adding a ton of features. Work away though if you think there are needed missing features. I think the main task is just keeping up with the Xamarin.Forms updates. In fact I don't know if many of the open issues are actual legitimate bugs or whether its down to issues or changes in the underlying framework.

**Pull request merged**
